### PR TITLE
Bunch of syntax fixes

### PR DESCRIPTION
**Pull request by Maks3w**
See commit descriptions for see what has been fixed

### CODE REVIEW

**Comment by Maks3w** [comment]
The change in the UriTemplate main class namespace is a BC\Break.

When release this should be tagged as `0.3.0` according the semantic versioning rules.

**Comment by rezigned** [comment]
@Maks3w thank you again :), I think according to semantic versioning BC changes will increase `MAJOR` number i.e. `1.x.x` unless we provide backward compatibility (increase `MINOR` i.e. `0.3.0`).

**Comment by Maks3w** [comment]
Versions prior to `1.0.0` are considered unstable

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

So for me is ok to just tune the minor version

**Comment by rezigned** [comment]
Ah, ok I'll just increase `minor` number. I have some question regarding namespace changes, I saw some project use `<vendor>/<service>` name style. e.g. https://github.com/silexphp/Silex use `Silex\Application` or `Pimple\Container` for their main class and some use `<vendor>\<service>\<service>` which I think it's a bit duplicate in the name.

What's your opinion on this one? should I keep the old one `Rize\UriTemplate` and provide `Rize\UriTemplate\UriTemplate` as subclass of the main one?

**Comment by Maks3w** [comment]
Shipping a whole complete namespace improve autoloaders a bit. For example Composer does not allow PSR-4 autoloading if the namespace does not end with the namespace sperator (trailing `\`)

Also I preffer don't repeat the namespace part in the class name. Many IDEs become crazy and can't resolve classes properly.

**Comment by rezigned** [comment]
Right, so I'll go with this option, keep `Rize\UriTemplate` intact, make `Rize\UriTemplate\UriTemplate` as subclass of `Rize\UriTemplate`. if this is ok, I'll create a new release after merging it?

**Comment by Maks3w** [comment]
Yes master

**Comment by rezigned** [comment]
Here you go https://github.com/rize/UriTemplate/releases/tag/0.3.0 and thank you :+1:

**Pull request merged**
